version: '3'

services:
  mysql_db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
 
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    tty: true
    restart: always
    depends_on:
      - mysql_db
    environment:
      - DJANGO_SETTINGS_MODULE=aplication.settings
      - DATABASE_NAME=site_db
      - DATABASE_USER=django
      - DATABASE_PASSWORD=12345678
      - DATABASE_HOST=mysql_db
      - DATABASE_PORT=3306
      # - CACHE_LOCATION=localhost:11211
      - EMAIL_HOST_USER=""
      - EMAIL_HOST_PASSWORD=""
      - ALLOWED_HOSTS=""
